#!/bin/bash
Userid=$(id -u)

if [ $Userid -ne 0 ]; then 
  echo "please run this command as root user"
  exit 1
fi

echo "Installing nginx"
 dnf install nginx -y

 if [$? -ne 0 ]; then 
  echo "installation failed"
  else 
  echo "installtion is sueccesful"

fi
dnf install mysql -y
if [$? -ne 0 ]; then 
  echo "installation failed"
  else 
  echo "installtion is sueccesful"

fi

dnf install nodejs -y
if [$? -ne 0 ]; then 
  echo "installation failed"
  else 
  echo "installtion is sueccesful"

fi
